### ISSUE TITLE
Async setup does not fallback to bundled file

### ISSUE THREAD

**Issue by SniroCode** [optimizely/swift-sdk#298]
in the official docs, it shows that if an async setup fails it goes through the sync process which is using the cache and if that does not exist then use the bundled file. in the swift implementation that does not happen, it goes to the cache but skips the bundled file.

here are the swift setup docs: https://docs.developers.optimizely.com/full-stack/docs/initialize-sdk-swift

![](https://files.readme.io/ee8b24d-initialize-asynchronous.png)

**Comment by jaeopt** [comment]
@SniroCode Thanks for reporting. Bundled datafile is not supported for async initialization flow (it's for synchronous initialization only). The doc is out of date. We'll fix the doc to be consistent with the SDK API.

**Comment by SniroCode** [comment]
Thanks for the quick response :).
Are you sure?, because it seems that this is the behavior described in all of your docs and not just in the swift SDK Docs. and it makes sense that you have a fallback method to a bundled file and not just relaying on a network call that might fail. 

Also, it works as described in the doc in the Android SDK, so I think that if the docs and android are configured that way, then it makes sense that this is the way it’s supposed to work.

**Comment by jaeopt** [comment]
@SniroCode Your observation is correct. The bundled datafile fallback for async init is still supported in the Android and ObjC SDK. 

We decided to drop this support for clarity in the Swift SDK. The bundled datafile may be used only when app is launched for the first time AND network fails. It's because in the async init, the SDK waits for the datafile download from the server. If it fails, it first falls back to the previously cached datafile. A cached datafile may not be available only when the app starts after install. Providing a bundled datafile support for this case only won't be helpful. That's why we decided to drop it for async init. 

Let us know if you see any other usage case, and then we can reconsider. Tx!

**Comment by SniroCode** [comment]
@jaeopt I do not see any other use cases.
But I think this is a pretty big use case, because it gives you the safety of a fallback method that is always there. what if the user launches the app for the first time and is phone is in a low service area or in airplane mode ? in most implementation the app would probably crash.

it is not such a big deal though the main thing for me that it is inconsistent with other platforms and that causes confusion.

**Comment by jaeopt** [comment]
@SniroCode App should be installed before the first time launch, so it's not likely app opens first time without network. Also even if it happens, the SDK stays in sdkNotReady state and app does not crash.

**Comment by SniroCode** [comment]
@jaeopt awesome! Thanks for taking the time and replying, much appreciated.
