### ISSUE TITLE
Incorrect Docs & Solution

### ISSUE THREAD

**Issue by Zanchee** [optimizely/swift-sdk#322]
https://docs.developers.optimizely.com/full-stack/docs/set-up-notification-listener-swift

The link states that...
>Keys and IDs can be accessed on OPTLYExperiment objects using experimentKey and experimentId respectively. Likewise, keys and IDs can be accessed on OPTLYVariation objects using variationKey and variationId.

`OPTLYExperiment` and `OPTLYVariation` do not exist in the Swift SDK and  their counterparts in. `addActivateNotificationListener` are `OptimizelyExperimentData` and OptimizelyVariationData` which are just `[String: Any]`. These dictionaries don't have any id keys like `experimentKey` or `variationKey` Should we be extending these ourselves, or are these outdated docs?

**Comment by jaeopt** [comment]
@Zanchee Thanks for reporting. The doc is outdated, which will be cleaned up. 
OptimizelyExperimentData and OptimizelyVariationData will include [key, id] pair each. 

It's strongly recommended to use "addDecisionNotificationListener" (instead of "addActivateNotificationListener") which is a set of new notifications we support including "activate" notification as well.

**Comment by jaeopt** [comment]
The doc has been updated
