### ISSUE TITLE
Experiment vs OptimizelyExperiment

### ISSUE THREAD

**Issue by Zanchee** [optimizely/swift-sdk#331]
I notice that `getOptimizelyConfig().experimentsMap` returns an map of `OptimizelyExperiment` which contains  some information, but  internally the `OptimizelyExperiment` type is actually an `Experiment` object that contains more useful information like  `status`. Why can't we access the `Experiment` object or  why doesn't `OptimizelyExperiment` contain all of the `Experiment` properties?

**Comment by Danny-Driscoll** [comment]
Our goal with the optimizelyConfig object is to provide data to enable the Feature and Experiment delivery use cases we are aware of, while holding back aspects of the underlying data model where our implementation may change over time. We are definitely open to feedback on additional useful fields to expose, but would love a bit more context on what you are looking to use them for. 

The status of an experiment specifically can be inferred as 'active' when they are in the datafile since only running experiments are included during datafile build.

**Comment by Zanchee** [comment]
Thanks for that info. Ideally I wouldn’t want to use the data file, but I need to be able to fetch the running experiments and their status to track with analytics in another platform. The data file was the only way that I saw via docs to get a kit of experiments and their statuses.

**Comment by Zanchee** [comment]
With the information you mentioned you’ve provided, it looks like I’m safe to move forward without needing status, but it is a bummer to have to use the data file. I love that in general Optimizely provides an interface that allows the client to ignore the details of experiments and just determine what features are enabled/disabled, but I think there are use cases where the client would also like to know what experiments are running without using the data file.

Thanks for getting back to me so quickly I really appreciate the insight you and your team have provided in a couple of questions I have had.

**Comment by Zanchee** [comment]
Sorry this took so long for me to get back. Thanks for explaining in more detail. I have relayed your message to the POs on my project and we have changed our requirements internally.
