### ISSUE TITLE
[ENHANCEMENT] Whitelist users for features

### ISSUE THREAD

**Issue by charlyliu** [optimizely/swift-sdk#551]
### Description

Similarly to experiments, I would like to be able to whitelist a list of users for QA purposes to automatically rollout a feature to these users instead of using the audience. Meaning these users will always be enabled. 

### Benefits

Same way to white list QA users for experiments and features.

**Comment by russell-loube-optimizely** [comment]
Hi @charlyliu , thanks for your feedback! Could you elaborate on the main challenge with using a dedicated audience for your QA testers in a feature rollout? Is it due to having to manager user IDs of your QA testers as audience attributes in code, on top of having to configure this audience in Full Stack/Feature Experimentation?

**Comment by charlyliu** [comment]
Hello @russell-loube-optimizely,
I was thinking that code wise when you have a feature why are you sending the user id again in the attributes when you already have it. But then for an experiment you are actually using the user id and you don't need to do an audience. 
I can see 2 benefits:
- no need to pass the user id twice every time you create a feature
- no need to change code when you run a feature experiment to send less data through the network. 

So with only `isFeatureEnabled(featureKey: "feature_a", userId: "abc")` you can rollout the feature to this user and force a variant to this user.
